"""phase 5: structures + inspection forms + inspections

Revision ID: 315bd26c645f
Revises: c857e1f4e0ad
Create Date: 2026-09-08 15:12:49.284011
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

revision: str = '315bd26c645f'
down_revision: Union[str, None] = 'c857e1f4e0ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_forms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('schema_json', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_forms_organisation_id'), 'inspection_forms', ['organisation_id'], unique=False)
    op.create_table('structures',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('structure_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('nearest_trail_id', sa.Uuid(), nullable=True),
    sa.Column('material', sa.String(length=64), nullable=False),
    sa.Column('installed_on', sa.Date(), nullable=True),
    sa.Column('inspection_interval_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('good', 'monitor', 'needs_repair', 'failed', 'decommissioned')", name='ck_structure_status'),
    sa.CheckConstraint("structure_type in ('culvert', 'bridge', 'boardwalk', 'ford', 'steps', 'retaining_wall', 'drain', 'waterbar', 'sign', 'gate', 'bench', 'kiosk', 'other')", name='ck_structure_type'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['nearest_trail_id'], ['trails.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # geom GIST index is created by GeoAlchemy2's spatial_index=True DDL event
    # on create_table - an explicit op.create_index here would collide.
    op.create_index(op.f('ix_structures_organisation_id'), 'structures', ['organisation_id'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('structure_id', sa.Uuid(), nullable=False),
    sa.Column('form_id', sa.Uuid(), nullable=True),
    sa.Column('form_version', sa.Integer(), nullable=True),
    sa.Column('inspector_id', sa.Uuid(), nullable=True),
    sa.Column('inspected_on', sa.Date(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('risk', sa.String(length=16), nullable=True),
    sa.Column('condition', sa.String(length=16), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('pdf_key', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("condition is null or condition in ('good', 'monitor', 'needs_repair', 'failed', 'decommissioned')", name='ck_inspection_condition'),
    sa.CheckConstraint("risk is null or risk in ('low', 'medium', 'high', 'critical')", name='ck_inspection_risk'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['form_id'], ['inspection_forms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['structure_id'], ['structures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_organisation_id'), 'inspections', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_inspections_project_id'), 'inspections', ['project_id'], unique=False)
    op.create_index(op.f('ix_inspections_structure_id'), 'inspections', ['structure_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inspections_structure_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_project_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_organisation_id'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_structures_organisation_id'), table_name='structures')
    op.drop_table('structures')
    op.drop_index(op.f('ix_inspection_forms_organisation_id'), table_name='inspection_forms')
    op.drop_table('inspection_forms')
    # ### end Alembic commands ###
