"""phase 1b: change_log sync spine

Revision ID: 619497572046
Revises: 0cc13f1890e2
Create Date: 2026-09-07 07:45:52.976211
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '619497572046'
down_revision: Union[str, None] = '0cc13f1890e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_log',
    sa.Column('server_seq', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('op', sa.String(length=8), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("op in ('upsert', 'delete')", name='ck_change_log_op'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('server_seq')
    )
    op.create_index('ix_change_log_org_seq', 'change_log', ['organisation_id', 'server_seq'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_change_log_org_seq', table_name='change_log')
    op.drop_table('change_log')
    # ### end Alembic commands ###
