"""phase 3: gpx tracks

Revision ID: 6f5c9508408f
Revises: 315bd26c645f
Create Date: 2026-09-09 09:58:03.077806
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

revision: str = '6f5c9508408f'
down_revision: Union[str, None] = '315bd26c645f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gpx_tracks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('activity', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('moving_seconds', sa.Integer(), nullable=False),
    sa.Column('geom', Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('points', sa.JSON(), nullable=False),
    sa.Column('recorded_by_id', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source in ('recorded', 'imported')", name='ck_gpx_track_source'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # geom GIST index is created by GeoAlchemy2's spatial_index=True DDL event
    # on create_table - an explicit op.create_index here would collide.
    op.create_index(op.f('ix_gpx_tracks_organisation_id'), 'gpx_tracks', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_gpx_tracks_project_id'), 'gpx_tracks', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gpx_tracks_project_id'), table_name='gpx_tracks')
    op.drop_index(op.f('ix_gpx_tracks_organisation_id'), table_name='gpx_tracks')
    op.drop_table('gpx_tracks')
    # ### end Alembic commands ###
