"""structure color

Revision ID: bf377e40071f
Revises: 6f5c9508408f
Create Date: 2026-09-09 12:15:32.839265
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bf377e40071f'
down_revision: Union[str, None] = '6f5c9508408f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'structures',
        sa.Column('color', sa.String(length=16), nullable=False, server_default=''),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('structures', 'color')
    # ### end Alembic commands ###
