"""phase 4: job types + segment work records

Revision ID: c857e1f4e0ad
Revises: 1827e37dc70e
Create Date: 2026-09-07 16:16:22.668073
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

revision: str = 'c857e1f4e0ad'
down_revision: Union[str, None] = '1827e37dc70e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('activity', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('unit', sa.String(length=8), nullable=False),
    sa.Column('default_crew', sa.Integer(), nullable=False),
    sa.Column('expected_rate', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('sort_group', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("unit in ('hours', 'km', 'm2', 'count')", name='ck_job_type_unit'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'activity', 'key', name='uq_job_type_key')
    )
    op.create_index(op.f('ix_job_types_organisation_id'), 'job_types', ['organisation_id'], unique=False)
    op.create_table('segment_work_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('job_type_id', sa.Uuid(), nullable=True),
    sa.Column('trail_id', sa.Uuid(), nullable=True),
    sa.Column('geom', Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=8), nullable=False),
    sa.Column('quantity_source', sa.String(length=8), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_seconds', sa.Integer(), nullable=False),
    sa.Column('pauses', sa.JSON(), nullable=False),
    sa.Column('crew_size', sa.Integer(), nullable=False),
    sa.Column('equipment', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("quantity_source in ('measured', 'manual')", name='ck_swr_quantity_source'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_type_id'], ['job_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trail_id'], ['trails.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # geom GIST index is created by GeoAlchemy2's spatial_index=True DDL event
    # on create_table - an explicit op.create_index here would collide.
    op.create_index(op.f('ix_segment_work_records_organisation_id'), 'segment_work_records', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_segment_work_records_project_id'), 'segment_work_records', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segment_work_records_project_id'), table_name='segment_work_records')
    op.drop_index(op.f('ix_segment_work_records_organisation_id'), table_name='segment_work_records')
    op.drop_table('segment_work_records')
    op.drop_index(op.f('ix_job_types_organisation_id'), table_name='job_types')
    op.drop_table('job_types')
    # ### end Alembic commands ###
